### ISSUE TITLE
travelers list may need to cross multiple departments (ie: CES)

### ISSUE THREAD

**Issue by mfrederickson** [KPB-US/tars#29]

**Comment by mfrederickson** [comment]
This has been accommodated by populating the extendedattribute7 with a comma separated list (no spaces around the comma) of the name of the departments they should be able to choose from.

**Comment by bjh45964** [comment]
Nicely done, thanks!


Ben Hanson
IT Director
Kenai Peninsula Borough
benhanson@kpb.us<mailto:benhanson@kpb.us>
907-714-2112

On Aug 19, 2016, at 4:11 PM, Marvin Frederickson <notifications@github.com<mailto:notifications@github.com>> wrote:


This has been accommodated by populating the extendedattribute7 with a comma separated list (no spaces around the comma) of the name of the departments they should be able to choose from.
